[tool.poetry]
name = "csv-transformer"
version = "0.1.0"
description = ""
authors = ["kkiyama117 <k.kiyama117@gmail.com>"]
readme = "README.md"
packages = [{include = "csv_transformer"}]

[tool.poetry.dependencies]
python = "^3.11"
polars = "^0.19.5"
chardet = "^5.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
